#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerates src/legacy/avb1_aosp_key.cpp from AOSP's public test key pair.

    gen_aosp_verity_key.py verity.pk8 verity.x509.pem > src/legacy/avb1_aosp_key.cpp

The inputs are `build/target/product/security/verity.pk8` and
`verity.x509.pem` from AOSP (platform/build, e.g. tag android-8.1.0_r1; newer
branches no longer carry them). They are the *public* "dev keys": the private
half has been in the open AOSP tree since 2014, which is exactly why Android
Image Kitchen, boot_signer and abr can use them as the default signer for
test builds. Needs only Python and the `openssl` command (to turn the PEM
certificate into DER).
"""
import hashlib
import subprocess
import sys


def c_array(name, data):
    lines = ["const uint8_t %s[] = {" % name]
    for i in range(0, len(data), 12):
        lines.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 12]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    pk8 = open(sys.argv[1], "rb").read()
    cert = subprocess.run(["openssl", "x509", "-in", sys.argv[2], "-outform", "DER"],
                          check=True, capture_output=True).stdout
    print("""// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/gen_aosp_verity_key.py -- do not edit by hand.
//
// AOSP's public "verity" dev key pair (build/target/product/security/
// verity.pk8 and verity.x509.pem), (c) The Android Open Source Project,
// Apache License 2.0. The private key is public knowledge; it is embedded
// only so abr can sign a boot image the way Android Image Kitchen does by
// default. Never use it for anything that has to stay trustworthy.
//
//   verity.pk8        sha256 %s
//   verity.x509 (DER) sha256 %s
#include "abr/legacy/avb1.hpp"

namespace abr::legacy::detail {

%s

const size_t kAospVerityPk8Size = sizeof(kAospVerityPk8);

%s

const size_t kAospVerityCertDerSize = sizeof(kAospVerityCertDer);

}  // namespace abr::legacy::detail
""" % (hashlib.sha256(pk8).hexdigest(), hashlib.sha256(cert).hexdigest(),
       c_array("kAospVerityPk8", pk8), c_array("kAospVerityCertDer", cert)))


main()
